### PR TITLE
Able to add Image in the DB

### PR DESCRIPTION
**Pull request by zaad97**
This pull request solved the issue #48 .
The way I did it is 
1. I made sure that the DB table row "POST" is using varbinary.
2. The row "POST' in the model 'UserPost' is in binary.
3. I slightly modified the form in Create.cshtml in the UserPost folder. I added the extra line in Html.BeginForm and for the POST div, instead of using razor code, i used regular HTML.
4. In UserPostsController.cs, I added a line in the Create [HttpPost] ActionResult. It is an if statement that check the image is not null and if it is true, it will convert the image in binary format.
5. In Index,cshtml in the UserPost folder, i added a code that convert binary to string.

### CODE REVIEW

**Comment by milanopatela** [comment]
Clean solution to remove excess files first please @zaad97

**Review by milanopatela — COMMENTED** [review]
Other then needed to clean solution its looks to be fine. Will test further before approving.

**Comment by milanopatela** [comment]
Merge complete. Will now check functionality from master. 
@zaad97 please provide sql code for userposts with updated varbinary

**Comment by zaad97** [comment]
No need the SQL in the project already has the POST has a varbinary.

**Comment by milanopatela** [comment]
no it doesn't. SQL database never changes even with git. its local to the computer

**Comment by milanopatela** [comment]
My mistake, @zaad97  updated the sql file in the github to have the updated version.

**Pull request merged**
