### PR TITLE
Milansprint4

### PR DESCRIPTION
**Pull request by milanopatela**
Added missing functionality for back end.
When the user now clicks like or dislikes, the record in UserPosts in the database has the likes/dislikes fields incremented or reduced respectve to the action.

### CODE REVIEW

**Comment by milanopatela** [comment]
@zaad97  need review

**Comment by zaad97** [comment]
All good. i do not see any problem. the like and dislike works as intended.
This pull request is ready to merge anytime.

**Comment by zaad97** [comment]
Database looks good, now that we added the new row. The rerouting for safety measure looks good.

Ok to merge the pull request.

**Review by milanopatela — COMMENTED** [review]
Looks good

**Pull request merged**
